version: '3.8'

services:
  api:
    container_name: nestjs_api
    build: '.'
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  db:
    container_name: nestjs_db
    image: postgres:14.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: test # Th
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - nesjs-network

networks:
  nesjs-network:
